### ISSUE TITLE
motif GO

### ISSUE THREAD

**Issue by sugiYag** [snystrom/dremeR#120]
The 'MEME suite' site says it has a function called Gene Ontology for Motifs (GOMO), but I wonder if the R package has not yet performed GO analysis with motif.

If possible, how should I analyze it?

**Comment by snystrom** [comment]
Unfortunately the `memes` R package does not support GOMO. I am unlikely to add support for this tool. 

In general I already think motifs discovered from bulk genomics data are a bit suspect (if the motif is from a DNA binding array or similar assay then I would be more confident), and I am also also quite wary of GO terms. I don't think statistical association of GO terms with motifs is a very good way to learn anything you can be confident in.

This approach might work better in prokaryotes or phage that have mostly promoter-proximal gene regulation, but for anything in eukaryotic organisms, I think you will struggle unless the motifs are literally right inside promoters (C elegans may be an exception here, since a majority of their gene regulatory program is promoter proximal).

Anyway, sorry for the bad news. You could still use the online tool or the command line version if you wanted to export the motifs from R.
